<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_da vinci code</name>
   <tag></tag>
   <elementGuidId>adb9119d-01c7-4bf8-a3b9-c10e9525899d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.s-suggestion.s-suggestion-ellipsis-direction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d51436ed-b6df-4390-99cb-3071e5d5afa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-suggestion s-suggestion-ellipsis-direction</value>
      <webElementGuid>911c652c-56e5-4b3c-9ef1-629235213a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4735d182-7f63-4b17-9d77-e8f1fb5fad8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>da vinci code</value>
      <webElementGuid>34562f8f-0925-4981-814d-43a43c72eba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>da vinci code</value>
      <webElementGuid>4ad759a3-3a21-4710-99ca-6470b1bda6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-searchAjax&quot;)/div[@class=&quot;autocomplete-results-container&quot;]/div[@class=&quot;two-pane-results-container&quot;]/div[@class=&quot;left-pane-results-container&quot;]/div[1]/div[@class=&quot;s-suggestion-container&quot;]/div[@class=&quot;s-suggestion s-suggestion-ellipsis-direction&quot;]</value>
      <webElementGuid>7d65d2de-16e6-4068-86ad-4cb0f5682aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div</value>
      <webElementGuid>eb7d7a8e-6df1-4f7c-b123-0b04f39be012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>d47f6b56-0064-43d5-a682-d172d77c52ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'da vinci code' or . = 'da vinci code')]</value>
      <webElementGuid>fd676f63-5e9f-4347-84df-679d4522cf1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
