<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__cropped-image-link_style_fluidLandscap_8e93c3</name>
   <tag></tag>
   <elementGuidId>b034e9e0-7eab-4dfa-87e6-5e80179e9421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstance61_Ud_vuBPA9Xvzox1M4Jw']/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CardInstance61_Ud_vuBPA9Xvzox1M4Jw > a.a-link-normal._cropped-image-link_style_centerImage__1rzYI.aok-block.image-window > div.a-section.a-spacing-none._cropped-image-link_style_fluidImageContainer__2jd50 > img._cropped-image-link_style_fluidLandscapeImage__3eTVC._cropped-image-link_style_fluidImage__iJ3aE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c154447-bdc6-497d-80f4-609a6d795371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Our Top 100+ Valentine’s Day gifts</value>
      <webElementGuid>d5feb0db-4cff-4848-8b80-8449c956d632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71nwqPZaNRL._SX3000_.jpg</value>
      <webElementGuid>5b98374e-7080-499b-9b5d-ed021f9bf52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_cropped-image-link_style_fluidLandscapeImage__3eTVC 
 _cropped-image-link_style_fluidImage__iJ3aE</value>
      <webElementGuid>e1211441-1911-40cc-a9bb-be6e91142212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71nwqPZaNRL._SX3000_.jpg</value>
      <webElementGuid>f59c7b1f-5892-4fba-af46-90ec189c4adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstance61_Ud_vuBPA9Xvzox1M4Jw&quot;)/a[@class=&quot;a-link-normal _cropped-image-link_style_centerImage__1rzYI aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none _cropped-image-link_style_fluidImageContainer__2jd50&quot;]/img[@class=&quot;_cropped-image-link_style_fluidLandscapeImage__3eTVC 
 _cropped-image-link_style_fluidImage__iJ3aE&quot;]</value>
      <webElementGuid>e6971817-527a-46d5-95e4-7c8604054c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstance61_Ud_vuBPA9Xvzox1M4Jw']/a/div/img</value>
      <webElementGuid>bce82569-a8fa-4b88-bc3f-5bd14fa1ec60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Our Top 100+ Valentine’s Day gifts']</value>
      <webElementGuid>04269414-c302-4ab3-a204-52d7c51944e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/a/div/img</value>
      <webElementGuid>2641be28-1c40-4919-91e1-f1fde85c7ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Our Top 100+ Valentine’s Day gifts' and @src = 'https://m.media-amazon.com/images/I/71nwqPZaNRL._SX3000_.jpg']</value>
      <webElementGuid>49d4c6af-fa90-44e6-bea1-29661d8b0360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
