<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.addToCart</name>
   <tag></tag>
   <elementGuidId>247df435-2b90-4c1d-a95a-f7f9cbd758d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.addToCart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.addToCart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e12712b-a6d1-42e4-98f9-a903168cf43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>504ddd3e-6ba1-41d6-a614-ddef6d3e661f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>7bfdab5f-d268-4f8b-bdd2-ac93b36b3c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asins</name>
      <type>Main</type>
      <value>[&quot;0385504209&quot;,&quot;0743486226&quot;,&quot;0385504225&quot;]</value>
      <webElementGuid>27104f37-66a6-42be-870c-b81dd76d6339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mix-operations</name>
      <type>Main</type>
      <value>AddToCart</value>
      <webElementGuid>01bbab32-9de3-4677-97a0-cd7c199ad654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numitems</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8b6bd13d-a038-4e77-8e83-b5ac8d4fa892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>pd_bxgy_crt</value>
      <webElementGuid>c1b434a3-1d3f-45b2-b040-7a5a69d3d6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=pd_bxgy_crt?_encoding=UTF8&amp;pd_rd_w=GzTgj&amp;content-id=amzn1.sym.839d7715-b862-4989-8f65-c6f9502d15f9&amp;pf_rd_p=839d7715-b862-4989-8f65-c6f9502d15f9&amp;pf_rd_r=966RXEGH438FRP2QNKVZ&amp;pd_rd_wg=jDmSY&amp;pd_rd_r=dfce3a93-292d-4fb9-be67-ab3e5f71e9cb</value>
      <webElementGuid>b93a2e85-f28c-4b0a-934e-5c09bef0ff04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>89877c9d-133c-421d-8503-7ae1cb41e8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-6-announce</value>
      <webElementGuid>8147d89c-06fb-4c98-a0a7-5ab2a338d3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-6&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>643b6434-8e12-4409-8f7a-d3c7e8e8c3c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.addToCart']</value>
      <webElementGuid>72dcf2b8-cf8b-44f1-a748-69bc559c2b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-6']/span/input</value>
      <webElementGuid>2b23dd31-33a6-44bc-9fb5-ad7825774334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/input</value>
      <webElementGuid>de256bbe-c0db-40b1-9c2d-fb4b86dab1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit.addToCart']</value>
      <webElementGuid>a6f6bd5b-8851-4eab-95a1-ab1915374d6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
