<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cvf_captcha_captcha_action</name>
   <tag></tag>
   <elementGuidId>ced1d96a-397a-4bde-81d9-922ae24ccb2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cvf_captcha_captcha_action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cvf_captcha_captcha_action&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>000ce96b-78b4-423b-b63b-5ae6a164484e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvf_captcha_captcha_action</value>
      <webElementGuid>9fe503e3-c779-47b1-9e9a-ff7ae152de4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input notranslate</value>
      <webElementGuid>53f3514b-8d38-4ac6-bfd3-1aaf301eb20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2f58f51d-8a58-467c-bbc5-1c4f0dbca777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>verifyCaptcha</value>
      <webElementGuid>d2f520e3-9690-408c-9143-141ade8a18b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>667e7bc6-bf0a-45d7-a0c2-53796588e87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input notranslate&quot;]</value>
      <webElementGuid>8af1c054-3e18-4035-9d69-758e9c4a5e53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cvf_captcha_captcha_action']</value>
      <webElementGuid>efe9b639-27ff-43c7-8a51-de5779138389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>d876fd29-09e7-4733-b34f-eaa1e7df51c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>48fdbd44-b403-4879-90b5-2e4938d0e8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cvf_captcha_captcha_action' and @type = 'submit']</value>
      <webElementGuid>2243f742-0b49-4c55-b3ef-e7dafbcb55cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
